name: Deploy MkDocs

on:
  push:
    branches:
      - main  # 或其他主分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site # The folder the action should deploy.